title: "Anfel Sara BOUACHAT"
email: sarabouachat@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" 
url: "https://saramin-bit.github.io" 
twitter_username: @SaraMin76081670
github_username:  saramin-bit

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
